name:                stripe-ng
version:             0.1.0.0
github:              "iand675/stripe-ng"
license:             BSD3
author:              "Ian Duncan"
maintainer:          "ian@iankduncan.com"
copyright:           "Ian Duncan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/iand675/stripe-ng#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- mtl
- text
- lens
- mtl
- unordered-containers
- http-api-data
- http-client
- http-client-tls
- http-types
- http-conduit
- conduit
- lens
- exceptions
- pretty-show
- tagged
- vector

default-extensions:
  - DeriveGeneric
  - OverloadedStrings
  - QuasiQuotes
  - RecordWildCards
  - TypeApplications
  - FlexibleContexts

library:
  source-dirs: src
  when:
  - condition: flag(strict-json-check)
    cpp-options: -DSTRICT_JSON_CHECK

executables:
  stripe-ng-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stripe-ng

tests:
  stripe-ng-test:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stripe-ng
    - tasty
    - tasty-discover
    - tasty-hspec
    - aeson
    - aeson-qq

flags:
  strict-json-check:
    description: Fail JSON decoding if properties are unused by results. Primarily intended for nightly automated testing.
    manual: true
    default: false
