resolver: lts-13.11

packages:
  - .

extra-deps:
  - ede-0.2.9
  - fused-effects-0.5.0.1
  - fused-effects-lens-0.2.0.0
  - fastsum-0.1.1.0
  - http-media-0.8.0.0

nix:
  path: [nixpkgs=./nix]
  packages:
    - zlib
